### ISSUE TITLE
Header files "nodalview.h" and "waveformview.h" missing from Git repository? (fails to compile)

### ISSUE THREAD

**Issue by hartwork** [BenPyton/NodalSoundEditor#5]
Hi again @BenPyton, interesting project! :+1: 

I tried to compile it on Linux but it fails with the following error:
```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/BenPyton/SoundGenerator
# cd SoundGenerator/
# qmake5 SoundGenerator.pro
# make -j5
[..]
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -IUI -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o MainWindow.o UI/MainWindow.cpp
[..]
In file included from UI/MainWindow.cpp:22:
./ui_mainwindow.h:25:10: fatal error: nodalview.h: No such file or directory
   25 | #include "nodalview.h"
      |          ^~~~~~~~~~~~~
[..]
```
It seems that files `nodalview.h` and `waveformview.h` are missing from the Git repository. Could you add them?

Thanks and best, Sebastian

**Comment by BenPyton** [comment]
Hi hartwork,

They are but the case is wrong in the header, you should put "NodalView.h" and "WaveFormView.h" instead.

On Linux it is an issue but not on Windows. I missed those ones when I changed the filename cases...

**Comment by hartwork** [comment]
@BenPyton didn't think of case insensitivity, I confirm, nice! Should I make a pull request with a fix? There's one more error at least, let's see if I can fix it…
